version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'daily'
      groups:
          root-dependencies:
              patterns:
                  - '*'
      assignees:
          - 'aditya-arcot'

    - package-ecosystem: 'npm'
      directory: 'shared'
      schedule:
          interval: 'daily'
      groups:
          shared-dependencies:
              patterns:
                  - '*'
      assignees:
          - 'aditya-arcot'

    - package-ecosystem: 'npm'
      directory: 'client'
      schedule:
          interval: 'daily'
      groups:
          client-dependencies:
              patterns:
                  - '*'
      assignees:
          - 'aditya-arcot'

    - package-ecosystem: 'npm'
      directory: 'server'
      schedule:
          interval: 'daily'
      groups:
          server-dependencies:
              patterns:
                  - '*'
      assignees:
          - 'aditya-arcot'

    - package-ecosystem: 'docker'
      directory: 'client'
      schedule:
          interval: 'weekly'
      groups:
          client-docker:
              patterns:
                  - '*'
      assignees:
          - 'aditya-arcot'

    - package-ecosystem: 'docker'
      directory: 'server'
      schedule:
          interval: 'weekly'
      groups:
          server-docker:
              patterns:
                  - '*'
      assignees:
          - 'aditya-arcot'

    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
      groups:
          github-actions:
              patterns:
                  - '*'
      assignees:
          - 'aditya-arcot'
