version: 2
registries:
    github-packages:
        type: npm-registry
        url: https://npm.pkg.github.com
        token: ${{ secrets.DEPENDABOT_GH_NPM_TOKEN }}
        replaces-base: true
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      registries: '*'
      schedule:
          interval: 'weekly'
      groups:
          root-dependencies:
              patterns:
                  - '*'
      assignees:
          - 'aditya-arcot'

    - package-ecosystem: 'npm'
      directory: 'shared'
      registries: '*'
      schedule:
          interval: 'weekly'
      groups:
          shared-dependencies:
              patterns:
                  - '*'
      assignees:
          - 'aditya-arcot'

    - package-ecosystem: 'npm'
      directory: 'client'
      registries: '*'
      schedule:
          interval: 'weekly'
      groups:
          client-dependencies:
              patterns:
                  - '*'
      assignees:
          - 'aditya-arcot'

    - package-ecosystem: 'npm'
      directory: 'server'
      registries: '*'
      schedule:
          interval: 'weekly'
      groups:
          server-dependencies:
              patterns:
                  - '*'
      assignees:
          - 'aditya-arcot'

    - package-ecosystem: 'docker'
      directory: 'client'
      schedule:
          interval: 'weekly'
      groups:
          client-docker:
              patterns:
                  - '*'
      assignees:
          - 'aditya-arcot'

    - package-ecosystem: 'docker'
      directory: 'server'
      schedule:
          interval: 'weekly'
      groups:
          server-docker:
              patterns:
                  - '*'
      assignees:
          - 'aditya-arcot'

    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
      groups:
          github-actions:
              patterns:
                  - '*'
      assignees:
          - 'aditya-arcot'
