name: ${REPO}
services:
    server:
        image: ${SERVER_IMAGE}
        ports:
            - '${SERVER_PORT}:3000'
        restart: always
        container_name: ${SERVER_CONTAINER}

    client:
        image: ${CLIENT_IMAGE}
        ports:
            - '${CLIENT_PORT}:80'
        restart: always
        container_name: ${CLIENT_CONTAINER}
