BEGIN;

CREATE SCHEMA core;

GRANT USAGE, CREATE ON SCHEMA core TO :user;

GRANT USAGE, CREATE ON SCHEMA core TO PUBLIC;

CREATE SCHEMA lookup;

GRANT USAGE, CREATE ON SCHEMA lookup TO :user;

GRANT USAGE, CREATE ON SCHEMA lookup TO PUBLIC;

CREATE SCHEMA debug;

GRANT USAGE, CREATE ON SCHEMA debug TO :user;

GRANT USAGE, CREATE ON SCHEMA debug TO PUBLIC;

DROP SCHEMA public;

COMMIT;