#!/bin/bash

if [ -z "$ENV_FILE" ]; then
    echo "ENV_FILE not set"
    exit 1
fi

if [ -f $ENV_FILE ]; then
    echo "loading .env"
    export $(grep -v '^#' $ENV_FILE | xargs)
fi

if [ -z "$DB_USER" ] || [ -z "$DB_PASSWORD" ] || [ -z "$DB_NAME" ]; then
    echo "error - one or more required env vars are not set"
    exit 1
fi

echo "done checking vars"
echo