#!/bin/bash

set -e

source ./load_env

if psql -lqt | cut -d \| -f 1 | grep -qw $DB_NAME; then
    echo "database already exists. dropping..."
    dropdb $DB_NAME
else
    echo "database does not exist"
fi
echo

echo "creating database"
createdb $DB_NAME
echo

echo "checking user"
if psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='$DB_USER';" | grep -q 1; then
    echo "user already exists. dropping..."
    psql postgres -c "DROP USER $DB_USER;"
else
    echo "user does not exist"
fi
echo

echo "creating user"
psql postgres -c "CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD';"
echo

echo "granting permissions"
psql $DB_NAME -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;"
echo

echo "creating tables"
PGPASSWORD=$DB_PASSWORD psql $DB_NAME -U $DB_USER -f $SCRIPTS_DIR/create_tables.sql -v ON_ERROR_STOP=1
echo

echo "seeding data"
PGPASSWORD=$DB_PASSWORD psql $DB_NAME -U $DB_USER -f $SCRIPTS_DIR/seed_data.sql -v ON_ERROR_STOP=1
echo

