#!/bin/bash

set -e

echo "removing global symlink..."
npm uninstall -g @aditya-arcot/wealthwatch-shared
echo 

echo "unlinking from client..."
cd ../client
npm unlink @aditya-arcot/wealthwatch-shared
echo

echo "reinstalling to client..."
npm install @aditya-arcot/wealthwatch-shared
echo

echo "unlinking from server..."
cd ../server
npm unlink @aditya-arcot/wealthwatch-shared
echo

echo "reinstalling to server..."
npm install @aditya-arcot/wealthwatch-shared
echo
