export enum StudentLoanStatusTypeEnum {
    Cancelled = 1,
    ChargedOff,
    Claim,
    Consolidated,
    Deferment,
    Delinquent,
    Discharged,
    Extension,
    Forbearance,
    InGrace,
    InMilitary,
    InSchool,
    NotFullyDisbursed,
    PaidInFull,
    Refunded,
    Repayment,
    Transferred,
    PendingIDR,
    Other,
}

export enum StudentLoanRepaymentPlanTypeEnum {
    Graduated = 1,
    Standard,
    ExtendedGraduated,
    ExtendedStandard,
    IncomeContingentRepayment,
    IncomeBasedRepayment,
    IncomeSensitiveRepayment,
    InterestOnly,
    PayAsYouEarn,
    RevisedPayAsYouEarn,
    SavingOnAValuableEducation,
    Other,
}
