#!/bin/sh

echo "Running pre-commit hook..."
echo

echo "Scanning for secrets in staged files..."
ggshield secret scan pre-commit "$@"
echo

echo "Formatting and linting staged files..."
lint-staged
echo

echo "Checking for dependency issues..."
echo "Checking base project..."
depcheck || exit 1
echo

echo "Checking shared project..."
depcheck shared || exit 1
echo

echo "Checking client project..."
depcheck client || exit 1
echo

echo "Checking server project..."
depcheck server || exit 1
echo

echo "Checking for available updates..."
echo "Checking base project..."
ncu -e 2 || exit 1
echo

echo "Checking shared project..."
ncu --cwd shared --configFilePath shared/.ncurc.json -e 2 || exit 1
echo

echo "Checking client project..."
ncu --cwd client --configFilePath client/.ncurc.json -e 2 || exit 1
echo

echo "Checking server project..."
ncu --cwd server --configFilePath server/.ncurc.json -e 2 || exit 1
echo

echo "Done running pre-commit hook"