name: Bump Shared Package Version

on:
    pull_request:
        branches:
            - main
        types:
            - closed
        paths:
            - 'shared/package.json'
            - 'shared/package-lock.json'

permissions:
    contents: write

jobs:
    bump-version:
        if: >
            github.event.pull_request.merged == true &&
            github.event.pull_request.user.login == 'dependabot[bot]'
        runs-on: self-hosted
        steps:
            - name: checkout
              uses: actions/checkout@v4
              with:
                  ref: main

            - name: setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 'lts/*'
                  check-latest: true
                  cache: 'npm'
                  cache-dependency-path: shared/package-lock.json

            - name: bump version
              run: |
                  cd shared/
                  npm version patch

            - name: commit and push changes
              run: |
                  cd shared/
                  git config --local user.email "github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"
                  git add package.json package-lock.json
                  git commit -m "bump shared package version after dependabot merge"
                  git push
