name: Bump and Publish Shared Package after Dependabot Merge

on:
    pull_request:
        branches:
            - stage
        types:
            - closed
        paths:
            - 'shared/package.json'
            - 'shared/package-lock.json'

permissions:
    contents: write
    packages: write

env:
    NPM_CONFIG_USERCONFIG: /dev/null

jobs:
    bump-and-publish:
        if: >
            github.event.pull_request.merged == true &&
            github.event.pull_request.user.login == 'dependabot[bot]'
        runs-on: self-hosted
        steps:
            - name: checkout
              uses: actions/checkout@v5

            - name: setup node
              uses: actions/setup-node@v5
              with:
                  node-version: 'lts/*'
                  check-latest: true
                  cache: 'npm'
                  cache-dependency-path: shared/package-lock.json

            - name: create .npmrc
              working-directory: shared
              run: |
                  echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_NPM_TOKEN }}" >> .npmrc
                  echo "@aditya-arcot:registry=https://npm.pkg.github.com/" >> .npmrc

            - name: fetch, rebase
              run: |
                  git fetch
                  git rebase

            - name: bump version
              working-directory: shared
              run: |
                  npm config ls
                  npm version patch

            - name: commit, push changes
              working-directory: shared
              run: |
                  git config --local user.email "github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"
                  git config list

                  git add package.json package-lock.json
                  git status

                  git commit -m "bump shared package version after dependabot merge"
                  git push

            - name: install, build
              working-directory: shared
              run: |
                  npm config ls
                  npm ci
                  npm run build

            - name: publish
              working-directory: shared
              run: |
                  npm config ls
                  npm whoami --registry=https://npm.pkg.github.com/
                  npm publish --access public
